### PR TITLE
deps: batch safe minor/patch upgrades + fix undici security override

### PR DESCRIPTION
**Pull request by s4lly**
Implements `docs/issues/001-safe-minors-and-undici-security.md`.

## Summary

- **Refresh in-range minor/patch frontend deps** to latest within their existing majors: react 19.2.x, all `@radix-ui/*`, `@tanstack/react-query` 5.101, framer-motion, jotai, zod 4.4, date-fns, posthog-js, react-image-crop, `@react-spring/web`, tailwind-merge, `@clerk/localizations`, plus dev deps (msw, prettier, eslint 10.6, typescript-eslint 8.x, `@types/*`). `react-router` / `react-router-dom` stay on **7.x**. No out-of-scope majors (Vite/Vitest, TS 6, Lingui 6, Tailwind 4, Clerk Core 3, Zero 1.x) pulled in.
- **Fix the undici security override.** A deep investigation found the existing override was **inert**: pnpm 10.17 no longer reads a top-level `overrides` block in a non-root `package.json`, so `undici: ^6.0.0` in `frontend/package.json` never applied (undici 5.28.4 / 5.29.0 / 6.23.0 still resolved). Moved the overrides to `pnpm-workspace.yaml` where pnpm honors them, and raised `undici` to `^6.27.0`. The tree now collapses to a single patched `undici@6.27.0`, clearing the Set-Cookie/SameSite advisory from `pnpm audit`. The `esbuild` and `react-router>path-to-regexp` overrides were moved alongside (also previously inert).
- Two files reformatted by the prettier 3.6→3.9 bump.

## Acceptance criteria

- [x] Listed minor/patch deps updated; `pnpm-lock.yaml` refreshed
- [x] `undici` override raised to `^6.27.0`; `pnpm audit` no longer reports the undici Set-Cookie/SameSite advisory
- [x] `react-router` / `react-router-dom` remain on 7.x
- [x] `pnpm --filter frontend run check` passes (lint 0 errors, format clean, type-check clean)
- [x] `pnpm --filter frontend run build` succeeds
- [ ] `pnpm --filter frontend run test` — see note below

## Test note

`useSplitPercent.test.tsx` fails with `Cannot find module 'babel-plugin-macros'`. This was verified (via a `main` worktree) to **fail identically on `main`** — same error, same 152-passed / 1-failed / 44-skipped counts. It's a pre-existing missing optional lingui peer introduced in #121, **not a regression from this upgrade**, and out of scope for this issue. Can be fixed as a follow-up (add `babel-plugin-macros` as a devDependency).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Bug Fixes**
  * Updated core app libraries and tooling to newer versions, helping improve stability and compatibility.
  * Added dependency overrides to keep select packages on known-good versions, reducing the risk of build or runtime issues.
* **Chores**
  * Refreshed development and testing dependencies across the project.

### CODE REVIEW

**Comment by s4lly** [comment]
@coderabbit pause

**Comment by s4lly** [comment]
@coderabbitai review

**Comment by s4lly** [comment]
@coderabbitai pause
